version: '3'

services:
  autoupdatecam:
    container_name: autoupdatecam
    image: jiuxiajingfan/cameraupload:latest
    volumes:
      - ./recordings:/app/recordings
    restart: always
    environment:
      TZ: ${TZ}
      CAMERA_IP: ${CAMERA_IP}
      CAMERA_PORT: ${CAMERA_PORT}
      CAMERA_USERNAME: ${CAMERA_USERNAME}
      CAMERA_PASSWORD: ${CAMERA_PASSWORD}
      CAMERA_STREAM: ${CAMERA_STREAM}
      RECORDING_OUTPUT_DIR: ${RECORDING_OUTPUT_DIR}
      RECORDING_SEGMENT_TIME: ${RECORDING_SEGMENT_TIME}
      RECORDING_START_HOUR: ${RECORDING_START_HOUR}
      RECORDING_START_MINUTE: ${RECORDING_START_MINUTE}
      RECORDING_END_HOUR: ${RECORDING_END_HOUR}
      RECORDING_END_MINUTE: ${RECORDING_END_MINUTE}
      UPLOAD_RETRY_COUNT: ${UPLOAD_RETRY_COUNT}
      UPLOAD_RETRY_DELAY: ${UPLOAD_RETRY_DELAY}
      UPLOAD_KEEP_LOCAL: ${UPLOAD_KEEP_LOCAL}
      UPLOAD_FILE_PATTERN: ${UPLOAD_FILE_PATTERN}
      UPLOAD_MAX_FILE_AGE: ${UPLOAD_MAX_FILE_AGE}
      UPLOAD_ALIST_URL: ${UPLOAD_ALIST_URL}
      UPLOAD_ALIST_USER: ${UPLOAD_ALIST_USER}
      UPLOAD_ALIST_PASS: ${UPLOAD_ALIST_PASS}
      UPLOAD_ALIST_PATH: ${UPLOAD_ALIST_PATH}
      UPLOAD_MAX_CONCURRENT: ${UPLOAD_MAX_CONCURRENT}
